config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "pages#home"

  resources :clients do
    resources :echantillons
    resources :prestations do
    end
  end

  resources :analyses

end

app/models/analyse.rb
class Analyse < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :analyses
  has_many :echantillons
end

app/models/echantillon.rb
class Echantillon < ApplicationRecord
  belongs_to :client
  has_many :analyses
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  belongs_to :client
end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    @client.save
    redirect_to clients_path()
  end

  def show
    @client = Client.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
  private
  def client_params
    params.require(:client).permit(:code, :society,:mail_contact,:mail_resultat,:amv)
  end
end

app/controllers/echantillons_controller.rb
class EchantillonsController < ApplicationController
  def index
  end

  def new
    @client = Client.find(params[:client_id])
    @echantillon = Echantillon.new
  end

  def create
    @client = Client.find(params[:client_id])
    @echantillon = Echantillon.new(echantillon_params)

    @echantillon.client = @client
    @echantillon.save
    redirect_to clients_path()
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def echantillon_params
    params.require(:echantillon).permit(:code,:description,:n_lot,:reception_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/prestations_controller.rb
class PrestationsController < ApplicationController
  def index
  end

  def new
    @client = Client.find(params[:client_id])
    @prestation = Prestation.new
  end

  def create
    @client = Client.find(params[:client_id])
    @prestation = Prestation.new(presta_params)

    @prestation.client = @client
    @prestation.save
    redirect_to clients_path()
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def presta_params
    params.require(:prestation).permit(:client_id,:code,:n_devis)
  end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/echantillons_helper.rb
module EchantillonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prestations_helper.rb
module PrestationsHelper
end

app/views/analyses/create.html.erb
<h1>Analyses#create</h1>
<p>Find me in app/views/analyses/create.html.erb</p>

app/views/analyses/destroy.html.erb
<h1>Analyses#destroy</h1>
<p>Find me in app/views/analyses/destroy.html.erb</p>

app/views/analyses/edit.html.erb
<h1>Analyses#edit</h1>
<p>Find me in app/views/analyses/edit.html.erb</p>

app/views/analyses/index.html.erb
<h1>Analyses#index</h1>
<p>Find me in app/views/analyses/index.html.erb</p>

app/views/analyses/new.html.erb
<h1>Analyses#new</h1>
<p>Find me in app/views/analyses/new.html.erb</p>

app/views/analyses/show.html.erb
<h1>Analyses#show</h1>
<p>Find me in app/views/analyses/show.html.erb</p>

app/views/analyses/update.html.erb
<h1>Analyses#update</h1>
<p>Find me in app/views/analyses/update.html.erb</p>

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/destroy.html.erb
<h1>Clients#destroy</h1>
<p>Find me in app/views/clients/destroy.html.erb</p>

app/views/clients/edit.html.erb
<h1>Clients#edit</h1>
<p>Find me in app/views/clients/edit.html.erb</p>

app/views/clients/index.html.erb
<h1>Clients#index</h1>
<p>Find me in app/views/clients/index.html.erb</p>
<table>
  <thead>
    <tr>
      <th>Code client</th>
      <th>Societe</th>
      <th>AMV</th>
      <th>Nombre d'échantillons</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
      <td><%= client.code %></td>
      <td><%= client.society %></td>
      <td><%= client.amv %></td>
      <td><%= client.echantillons.size %></td>
      <td><%= link_to "Nouvel échantillon",new_client_echantillon_path(client)%></td>
      <td><%= link_to "Nouvelle prestation",new_client_prestation_path(client)%></td>
      </tr>
    <%end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<h1>Clients#new</h1>
<p>Find me in app/views/clients/new.html.erb</p>
<%= simple_form_for @client do |f|%>
  <%= f.input :code %>
  <%= f.input :society %>
  <%= f.input :mail_contact %>
  <%= f.input :mail_resultat %>
  <%= f.input :amv %>
  <%= f.button :submit %>
<% end %>

app/views/clients/show.html.erb
<h1>Clients#show</h1>
<p>Find me in app/views/clients/show.html.erb</p>
<%= link_to "Nouvelle prestation",new_client_prestation_path()%>

app/views/clients/update.html.erb
<h1>Clients#update</h1>
<p>Find me in app/views/clients/update.html.erb</p>

app/views/echantillons/create.html.erb
<h1>Echantillons#create</h1>
<p>Find me in app/views/echantillons/create.html.erb</p>

app/views/echantillons/destroy.html.erb
<h1>Echantillons#destroy</h1>
<p>Find me in app/views/echantillons/destroy.html.erb</p>

app/views/echantillons/edit.html.erb
<h1>Echantillons#edit</h1>
<p>Find me in app/views/echantillons/edit.html.erb</p>

app/views/echantillons/index.html.erb
<h1>Echantillons#index</h1>
<p>Find me in app/views/echantillons/index.html.erb</p>

app/views/echantillons/new.html.erb
<h1>Echantillons#new</h1>
<p>Find me in app/views/echantillons/new.html.erb</p>
<%= @client.society %>
<hr>
<%= simple_form_for [@client,@echantillon] do |f|%>
  <%= f.input :code,label:"code echantillon client" %>
  <%= f.input :description %>
  <%= f.input :n_lot %>
  <%= f.input :reception_date %>
  <%= f.button :submit %>
<% end %>

app/views/echantillons/show.html.erb
<h1>Echantillons#show</h1>
<p>Find me in app/views/echantillons/show.html.erb</p>

app/views/echantillons/update.html.erb
<h1>Echantillons#update</h1>
<p>Find me in app/views/echantillons/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Erp Phytodia" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Nouveau client",new_client_path() %>
<%= link_to "Liste des clients",clients_path() %>

app/views/prestations/create.html.erb
<h1>Prestations#create</h1>
<p>Find me in app/views/prestations/create.html.erb</p>

app/views/prestations/destroy.html.erb
<h1>Prestations#destroy</h1>
<p>Find me in app/views/prestations/destroy.html.erb</p>

app/views/prestations/edit.html.erb
<h1>Prestations#edit</h1>
<p>Find me in app/views/prestations/edit.html.erb</p>

app/views/prestations/index.html.erb
<h1>Prestations#index</h1>
<p>Find me in app/views/prestations/index.html.erb</p>

app/views/prestations/new.html.erb
<h1>Prestations#new</h1>
<p>Find me in app/views/prestations/new.html.erb</p>
<%= simple_form_for [@client,@prestation] do |f|%>
  <%= f.input :code %>
  <%= f.input :n_devis %>
  <%= f.button :submit %>
<% end %>

app/views/prestations/show.html.erb
<h1>Prestations#show</h1>
<p>Find me in app/views/prestations/show.html.erb</p>

app/views/prestations/update.html.erb
<h1>Prestations#update</h1>
<p>Find me in app/views/prestations/update.html.erb</p>